CREATE DATABASE peereval CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

use peereval;

SET FOREIGN_KEY_CHECKS= 0;

CREATE TABLE evaluation_form (id INT AUTO_INCREMENT NOT NULL, attemptAt DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB;
CREATE TABLE answer (id INT AUTO_INCREMENT NOT NULL, form_id INT DEFAULT NULL, answer SMALLINT NOT NULL, INDEX IDX_DADD4A255FF69B7D (form_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB;
CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(20) NOT NULL, password VARCHAR(60) NOT NULL, email VARCHAR(255) NOT NULL, firstName VARCHAR(20) NOT NULL, lastName VARCHAR(20) NOT NULL, role VARCHAR(255) NOT NULL, isVerified SMALLINT NOT NULL, verifyCode VARCHAR(255) DEFAULT NULL, registerAt DATETIME DEFAULT NULL, UNIQUE INDEX username (username), UNIQUE INDEX email (email), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB;
CREATE TABLE question (id INT AUTO_INCREMENT NOT NULL, template_form_id INT DEFAULT NULL, question LONGTEXT NOT NULL, INDEX IDX_B6F7494EC4EE044 (template_form_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB;
CREATE TABLE template_form (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, INDEX IDX_8746D722A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB;
CREATE TABLE form (id INT AUTO_INCREMENT NOT NULL, form_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, addedAt DATETIME NOT NULL, expiryAt DATETIME NOT NULL, INDEX IDX_5288FD4F5FF69B7D (form_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB;
CREATE TABLE person (id INT AUTO_INCREMENT NOT NULL, form_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, uniqueCode VARCHAR(255) NOT NULL, token VARCHAR(255) NOT NULL, registerAt DATETIME NOT NULL, INDEX IDX_34DCD1765FF69B7D (form_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB;
ALTER TABLE answer ADD CONSTRAINT FK_DADD4A255FF69B7D FOREIGN KEY (form_id) REFERENCES evaluation_form (id);
ALTER TABLE question ADD CONSTRAINT FK_B6F7494EC4EE044 FOREIGN KEY (template_form_id) REFERENCES template_form (id);
ALTER TABLE template_form ADD CONSTRAINT FK_8746D722A76ED395 FOREIGN KEY (user_id) REFERENCES user (id);
ALTER TABLE form ADD CONSTRAINT FK_5288FD4F5FF69B7D FOREIGN KEY (form_id) REFERENCES template_form (id);
ALTER TABLE person ADD CONSTRAINT FK_34DCD1765FF69B7D FOREIGN KEY (form_id) REFERENCES form (id);

INSERT INTO user (username,password,email,firstName,lastName,role,isVerified,verifyCode,registerAt)
VALUES ('peereval','$2y$16$HokVx6PYtzLdVaMIj71NZ.uP.CtCI2PMfgHYkEHTlYfxc/PFIKt5O','peereval.me@gmail.com','peer','eval','ROLE_ADMIN',1,null,now());

SET FOREIGN_KEY_CHECKS= 1;
