CREATE DATABASE peereval CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

use peereval;

SET FOREIGN_KEY_CHECKS= 0;

CREATE TABLE evaluation_form (
	id INT AUTO_INCREMENT NOT NULL, 
	team_id INT DEFAULT NULL, 
	person_id INT DEFAULT NULL, 
	attemptAt DATETIME NOT NULL, 
	INDEX IDX_1FCEB2F7296CD8AE (team_id), 
	INDEX IDX_1FCEB2F7217BBB47 (person_id), 
	PRIMARY KEY(id)
	) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB;

CREATE TABLE answer (
	id INT AUTO_INCREMENT NOT NULL, 
	person_id INT DEFAULT NULL, 
	form_id INT DEFAULT NULL, 
	answer SMALLINT NOT NULL, 
	INDEX IDX_DADD4A25217BBB47 (person_id), 
	INDEX IDX_DADD4A255FF69B7D (form_id), 
	PRIMARY KEY(id)
	) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB;

CREATE TABLE user (
	id INT AUTO_INCREMENT NOT NULL, 
	username VARCHAR(20) NOT NULL, 
	password VARCHAR(60) NOT NULL, 
	email VARCHAR(255) NOT NULL,
	firstName VARCHAR(20) NOT NULL, 
	lastName VARCHAR(20) NOT NULL, 
	role VARCHAR(255) NOT NULL, 
	isVerified SMALLINT NOT NULL, 
	verifyCode VARCHAR(255) DEFAULT NULL, 
	registerAt DATETIME DEFAULT NULL, 
	UNIQUE INDEX username (username), 
	UNIQUE INDEX email (email), 
	PRIMARY KEY(id)
	) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB;

CREATE TABLE team (
	id INT AUTO_INCREMENT NOT NULL, 
	form_id INT DEFAULT NULL, 
	name VARCHAR(255) NOT NULL, 
	addedAt DATETIME NOT NULL, 
	expiryAt DATETIME NOT NULL, 
	INDEX IDX_C4E0A61F5FF69B7D (form_id), 
	PRIMARY KEY(id)
	) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB;

CREATE TABLE question (
	id INT AUTO_INCREMENT NOT NULL, 
	form_id INT DEFAULT NULL, 
	question LONGTEXT NOT NULL, 
	INDEX IDX_B6F7494E5FF69B7D (form_id), 
	PRIMARY KEY(id)
	) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB;

CREATE TABLE form (
	id INT AUTO_INCREMENT NOT NULL, 
	user_id INT DEFAULT NULL, 
	name VARCHAR(255) NOT NULL, 
	INDEX IDX_5288FD4FA76ED395 (user_id), 
	PRIMARY KEY(id)
	) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB;

CREATE TABLE person (
	id INT AUTO_INCREMENT NOT NULL, 
	team_id INT DEFAULT NULL, 
	name VARCHAR(255) NOT NULL, 
	email VARCHAR(255) NOT NULL,
	uniqueCode VARCHAR(255) NOT NULL, 
	token VARCHAR(255) NOT NULL, 
	registerAt DATETIME NOT NULL, 
	INDEX IDX_34DCD176296CD8AE (team_id), 
	PRIMARY KEY(id)
	) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB;

ALTER TABLE evaluation_form ADD 
CONSTRAINT FK_1FCEB2F7296CD8AE 
FOREIGN KEY (team_id) 
REFERENCES team (id);

ALTER TABLE evaluation_form ADD 
CONSTRAINT FK_1FCEB2F7217BBB47 
FOREIGN KEY (person_id) 
REFERENCES person (id);

ALTER TABLE answer ADD 
CONSTRAINT FK_DADD4A25217BBB47 
FOREIGN KEY (person_id) 
REFERENCES person (id);

ALTER TABLE answer ADD 
CONSTRAINT FK_DADD4A255FF69B7D 
FOREIGN KEY (form_id) 
REFERENCES evaluation_form (id);

ALTER TABLE team ADD 
CONSTRAINT FK_C4E0A61F5FF69B7D 
FOREIGN KEY (form_id) 
REFERENCES form (id);

ALTER TABLE question ADD 
CONSTRAINT FK_B6F7494E5FF69B7D 
FOREIGN KEY (form_id) 
REFERENCES form (id);

ALTER TABLE form ADD 
CONSTRAINT FK_5288FD4FA76ED395 
FOREIGN KEY (user_id) 
REFERENCES user (id);

ALTER TABLE person ADD 
CONSTRAINT FK_34DCD176296CD8AE 
FOREIGN KEY (team_id) 
REFERENCES team (id);

INSERT INTO user (username,password,email,firstName,lastName,role,isVerified,verifyCode,registerAt)
VALUES ('peereval','$2y$16$HokVx6PYtzLdVaMIj71NZ.uP.CtCI2PMfgHYkEHTlYfxc/PFIKt5O','peereval.me@gmail.com','peer','eval','ROLE_ADMIN',1,null,now());

SET FOREIGN_KEY_CHECKS= 1;