<?php

namespace AppBundle\Repository;

/**
 * EvaluationAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluationAnswerRepository extends \Doctrine\ORM\EntityRepository
{
}
