<?php

namespace AppBundle\Repository;

/**
 * EvaluationQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluationQuestionRepository extends \Doctrine\ORM\EntityRepository
{
}
