<?php

namespace AppBundle\Repository;

/**
 * FormQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormQuestionRepository extends \Doctrine\ORM\EntityRepository
{
}
