<?php

namespace AppBundle\Repository;

/**
 * FormAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormAnswerRepository extends \Doctrine\ORM\EntityRepository
{
}
