<?php

namespace AppBundle\Repository;

/**
 * QuestionMainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionMainRepository extends \Doctrine\ORM\EntityRepository
{
}
