<?php

namespace AppBundle\Repository;

/**
 * RegisterStudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegisterStudentRepository extends \Doctrine\ORM\EntityRepository
{
}
