<?php

namespace AppBundle\Repository;

/**
 * TemplateQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemplateQuestionRepository extends \Doctrine\ORM\EntityRepository
{
}
