<?php

namespace AppBundle\Repository;

/**
 * TemplateFormRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemplateFormRepository extends \Doctrine\ORM\EntityRepository
{
}
