<?php

namespace AppBundle\Repository;

use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;
use Symfony\Component\Security\Core\Exception\UsernameNotFoundException;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository implements UserLoaderInterface
{
    public function loadUserByUsername($username)
    {
    	if(null !== $this->property){
    		$user = $this->repository->findOneBy(array($this->propert => $username));
    	} else {
    		if (!$this->repository instanceof UserLoadInterface){
    			throw new InvalidArgumentException();
    		}
    		$user = $this->repository->loadUserByUsername($username);
    	}

    	if(null === $user){
    		throw new UsernameNotFoundException(sprintf('User "%s" not found.',$username));
    	}

    	return $user;
    }
}