<?php

namespace AppBundle\Repository;

use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;
use Symfony\Component\Security\Core\Exception\UsernameNotFoundException;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository implements UserLoaderInterface
{
	/**
	 * [loadUserByUsername fetch username is database]
	 * @param  string $username
	 * @return string
	 */
	public function loadUserByUsername($username)
	{	
		//fetch username
		//where username can be username or email
		$user = $this->createQueryBuilder('u')
			->where('u.username = :username OR u.email = :email')
			->setParameter('username', $username)
			->setParameter('email', $username)
			->getQuery()
			->getOneorNullResult();
			
		return $user; //return user
	}
}
