# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\User:
          algorithm: bcrypt
          cost: 16
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        #in_memory:
          #memory:

        database:
            entity:
                class: AppBundle:User

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
            
            http_basic:
                provider: database

            guard:
              authenticators:
                - app.form_login_authenticators

            logout:
                path: /logout
                target: /

    access_control:
        - {path: ^/register, roles: ROLE_ADMIN }
        - {path: ^/dashboard, roles: [ROLE_USER, ROLE_ADMIN] }
        - {path: ^/dashboard/diy-form, roles: [ROLE_USER, ROLE_ADMIN] }
        - {path: ^/dashboard/pre-form, roles: [ROLE_USER, ROLE_ADMIN] }
        - {path: ^/review, roles: [ROLE_USER, ROLE_ADMIN] }
        - {path: ^/evaluate, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - {path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
